// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentConfig() {
  return window['go']['main']['Config']['GetCurrentConfig']();
}

export function GetPaths(arg1) {
  return window['go']['main']['Config']['GetPaths'](arg1);
}

export function GetSaves(arg1) {
  return window['go']['main']['Config']['GetSaves'](arg1);
}

export function WriteConfig(arg1) {
  return window['go']['main']['Config']['WriteConfig'](arg1);
}
