// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCurrentConfig():Promise<main.Config>;

export function GetPaths(arg1:main.Config):Promise<string>;

export function GetSaves(arg1:main.Config):Promise<Array<number>>;

export function WriteConfig(arg1:main.Config):Promise<void>;
