// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadFile(arg1:string,arg2:main.Config):Promise<string>;

export function GetOrgName(arg1:main.Config,arg2:number):Promise<string>;

export function ReadConfig(arg1:string):Promise<main.Config>;

export function ReadJSONField(arg1:string,arg2:string):Promise<any>;

export function UnzipFile(arg1:string,arg2:main.Config):Promise<void>;

export function UploadFile(arg1:string,arg2:main.Config):Promise<void>;

export function ZipDirectory(arg1:main.Config,arg2:string):Promise<string>;
