// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['utils']['DownloadFile'](arg1, arg2);
}

export function GetOrgName(arg1, arg2) {
  return window['go']['main']['utils']['GetOrgName'](arg1, arg2);
}

export function ReadConfig(arg1) {
  return window['go']['main']['utils']['ReadConfig'](arg1);
}

export function ReadJSONField(arg1, arg2) {
  return window['go']['main']['utils']['ReadJSONField'](arg1, arg2);
}

export function UnzipFile(arg1, arg2) {
  return window['go']['main']['utils']['UnzipFile'](arg1, arg2);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['utils']['UploadFile'](arg1, arg2);
}

export function ZipDirectory(arg1, arg2) {
  return window['go']['main']['utils']['ZipDirectory'](arg1, arg2);
}
